# Generated by Django 4.2.4 on 2023-09-08 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='centerInterest',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='New group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='imageGroup',
            field=models.FileField(blank=True, null=True, upload_to='assets/imagesgroup/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='places',
            field=models.CharField(default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercreategroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
